[package]
name = "nyt_api"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.145"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.47", features = ["full"] }
