[package]
name = "flappy_xo9a8"
version = "0.1.0"
authors = ["XO9A8"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bracket-lib = "~0.8.7"
