[package]
name = "party_perticipants_screener"
version = "0.1.0"
edition = "2021"
authors = ["XO9A8"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
